#' Read annotations from GPT
#'
#' Read in phenotype annotations generated by GPT and
#'  do some initial preprocessing (e.g. adding HPO IDs).
#' @inheritParams main
#' @param save_path Path to annotations CSV file.
#'  If the file does not exist, the data will be downloaded from GitHub.
#' @param force_new If \code{TRUE}, the data will be downloaded from GitHub
#' even if it already exists locally.
#' @param verbose Print messages.
#' @param include_nogenes Include phenotypes with no associated genes.
#' @returns data.table of phenotype annotations
#'
#' @export
#' @examples
#' annot <- gpt_annot_read()
gpt_annot_read <- function(save_path=file.path(
  KGExplorer::cache_dir(package = "HPOExplorer"),
  "gpt4_hpo_annotations.csv"
),
                           force_new=FALSE,
hpo=get_hpo(),
include_nogenes=TRUE,
                           verbose=TRUE){
  pheno_count <- hpo_name <- hpo_id <- phenotype <- NULL;

  if(!file.exists(save_path) || isTRUE(force_new)){
    path <- paste0(
      "https://github.com/neurogenomics/RareDiseasePrioritisation/raw/master/",
      "gpt_annotations/gpt4_hpo_annotations.csv"
    )
    utils::download.file(path, save_path)
    # path <- get_data("gpt4_hpo_annotations.csv")
  }
  d <- data.table::fread(save_path, header = TRUE)
  d <- d[!is.na(phenotype)]
  data.table::setnames(d,"phenotype","hpo_name")
  d <- add_hpo_id(d, hpo = hpo)
  #### Check phenotype names ####
  annot <- load_phenotype_to_genes(verbose = verbose)
  d <- merge(d,
             unique(annot[,c("hpo_id","hpo_name")]),
             all.x = TRUE,
             by=c("hpo_name","hpo_id"))
  d <- data.frame(d)
  d[d==""] <- NA
  d <- data.table::data.table(d)
  d[,pheno_count:=table(d$hpo_name)[hpo_name]]
  #### Ensure no phenos are missing HPO IDs ####
  missing_phenos <- length(unique(d[is.na(hpo_id)]$hpo_name))
  if(missing_phenos>0){
    messager(missing_phenos,
             "phenotypes do not have matching HPO IDs.",v=verbose)
  }
  messager("Reading in GPT annotations for",
           formatC(length(unique(d$hpo_id)),big.mark = ","),
           "phenotypes.",
           v=verbose)
  # phenotype_miss_rate <-
  #   length(d$phenotype[!d$phenotype %in% annot$hpo_name]) /
  #   length(d$phenotype)
  return(d)
}
