#' Read annotations from GPT
#'
#' Read in phenotype annotations generated by GPT and
#'  do some initial preprocessing (e.g. adding HPO IDs).
#' @param path Path to annotations CSV file.
#'  If \code{NULL}, will pull data from GitHub Releases instead.
#' @param verbose Print messages.
#' @source code {
#' piggyback::pb_upload(file = "~/Downloads/gpt4_hpo_annotations.csv",
#'                      repo = "neurogenomics/HPOExplorer",
#'                      overwrite = TRUE,
#'                      tag = "latest")
#' }
#' @returns data.table of phenotype annotations
#'
#' @export
#' @examples
#' annot <- gpt_annot_read()
gpt_annot_read <- function(path = NULL,
                           verbose=TRUE){
  pheno_count <- hpo_name <- hpo_id <- NULL;

  if(is.null(path)){
    # path <- paste0(
    #   "https://github.com/neurogenomics/RareDiseasePrioritisation/raw/master/",
    #   "gpt_annotations/gpt4_hpo_annotations.csv"
    # )
    path <- get_data("gpt4_hpo_annotations.csv")
  }
  d <- data.table::fread(path, header = TRUE)
  data.table::setnames(d,"phenotype","hpo_name")
  #### Check phenotype names ####
  annot <- load_phenotype_to_genes(verbose = verbose)
  d <- merge(d,
             unique(annot[,c("hpo_id","hpo_name")]),
             by="hpo_name")
  d <- data.frame(d)
  d[d==""] <- NA
  d <- data.table::data.table(d)
  d[,pheno_count:=table(d$hpo_name)[hpo_name]]
  #### Ensure no phenos are missing HPO IDs ####
  missing_phenos <- length(unique(d[is.na(hpo_id)]$hpo_name))
  if(missing_phenos>0){
    messager(missing_phenos,
             "phenotypes do not have matching HPO IDs.",v=verbose)
  }
  messager("Reading in GPT annotations for",
           formatC(length(unique(d$hpo_id)),big.mark = ","),
           "phenotypes.",
           v=verbose)
  # phenotype_miss_rate <-
  #   length(d$phenotype[!d$phenotype %in% annot$hpo_name]) /
  #   length(d$phenotype)
  return(d)
}
