#' Map uPheno plot
#'
#' Generate multiple kinds of plots summarising mappings of phenotypes and genes
#' between the HPO and various non-human ontologies within uPheno.
#' @param types A character vector of plot types to generate.
#' @param pheno_map_genes_match uPheno cross-species mapping data generated by
#' \link[HPOExplorer]{map_upheno_data}.
#' @param subset_db1 A character vector of reference ontologies to subset
#' \code{pheno_map_genes_match} by.
#' @returns A named list of \pkg{ggplot2} objects.
#'
#' @export
#' @examples
#' pheno_map_genes_match <- map_upheno_data()
#' upheno_plots <- map_upheno_plot(
#'   pheno_map_genes_match = pheno_map_genes_match)
map_upheno_plot <- function(pheno_map_genes_match=NULL,
                            subset_db1="HP",
                            types=c("rainplot","scatterplot","heatmap")){
  ## Prepare plot data
  n_phenotypes <- db1 <- id1 <-NULL;
  {
    #### Subset data ####
    if(!is.null(subset_db1)) {
      plot_dat <- pheno_map_genes_match[db1 %in% subset_db1,]
      messager(data.table::uniqueN(plot_dat$subject_taxon_label2),"/",
               data.table::uniqueN(pheno_map_genes_match$subject_taxon_label2),
               "species remain after filtering by `subset_db1`.")
    }else {
      plot_dat <- data.table::copy(pheno_map_genes_match)
    }
    ## Only use one phenotype-phenotype per row
    plot_dat <- plot_dat[,.SD[1],by=c("db1","id1","db2","id2")]
    ## Recompute n_phenotypes
    plot_dat[,n_phenotypes:=data.table::uniqueN(id1),
             by=c("db1","db2",
                  "subject_taxon1","subject_taxon2",
                  "subject_taxon_label1","subject_taxon_label2"
             )]
  }
  plots <- list()
  if("rainplot" %in% types){
    plots[["rainplot"]] <- map_upheno_rainplot(plot_dat = plot_dat)
  }
  if("scatterplot" %in% types){
    plots[["scatterplot"]] <- map_upheno_scatterplot(plot_dat = plot_dat)
  }
  if("heatmap" %in% types){
    plots[["heatmap"]] <- map_upheno_heatmap(plot_dat = plot_dat)
  }
  return(plots)
}
