#' 3D network
#'
#' Plot a subset of the HPO as a 3D network.
#' @param g \link[igraph]{igraph} object
#' generated by \link[HPOExplorer]{make_igraph_object}.
#' @param layout_func Layout function for the graph.
#' @param extend_kde Extend the area that the
#' kernel density estimation (KDE) plot
#' (i.e. the "mountains" underneath the points) covers.
#' @param add_labels Add phenotype name labels to each point.
#' @returns plotly object.
#'
#' @source
#' \href{https://www.r-bloggers.com/2013/09/network-visualization-part-4-3d-networks/}{
#' R bloggers}
#' @source
#' \href{https://community.plotly.com/t/is-it-possible-to-connect-scatters-in-3d-scatter-plot/}{
#' Plotly: Connect points in 3D plot}
#' @source \href{https://plotly.com/r/line-charts/}{
#' Plotly: Connect points in 2D plot}
#' @source \href{https://plotly.com/r/3d-line-plots/}{
#' Plotly: 3D lines plots}
#'
#' @export
#' @importFrom stringr str_wrap
#' @examples
#' phenos <- make_phenos_dataframe(ancestor = "Neurodevelopmental delay")
#' g <- make_igraph_object(phenos = phenos)
#' plt <- network_3d(g=g)
network_3d <- function(g,
                       layout_func = igraph::layout.fruchterman.reingold,
                       extend_kde = 1.2,
                       add_labels = FALSE){

  # anc <- "Abnormality of the nervous system"
  # phenos <- make_phenos_dataframe(ancestor = anc)[ancestor_name==anc,]
  # g <- make_igraph_object(phenos = phenos)
  requireNamespace("plotly")
  requireNamespace("igraph")
  requireNamespace("pals")
  requireNamespace("MASS")
  requireNamespace("scales")
  label <- Phenotype <- NULL;

  layout_coords <- cbind(
    name=names(igraph::V(g)),
    layout_func(g,dim=3) |>
      data.table::as.data.table()|>
      `colnames<-`(c("x","y","z"))
  )
  df <- merge(
    layout_coords,
    data.table::data.table(ggnetwork::fortify(g))[,-c("x","y","xend","yend")],
    by="name"
  )
  df[,label:=gsub("\n","<br>",stringr::str_wrap(Phenotype, width = 20))]
  # hover_vars <- c("HPO_ID","Phenotype",
  #                 "ancestor_name","ontLvl",
  #                 "definition")
  kd <- MASS::kde2d(x = df$x,
                    y = df$y,
                    n = 50,
                    lims = c(range(df$x)*extend_kde,
                             range(df$y)*extend_kde))
  kd$z <- scales::rescale(x = kd$z, to = c(min(df$z*2),min(df$z)-.25))
  colors <- pals::kovesi.cyclic_mrybm_35_75_c68(length(unique(df$ontLvl)))
  fig <- df |>
    plotly::plot_ly(x = ~x,
                    y = ~y,
                    z = ~z ) |>
    plotly::add_markers(symbol = ~stringr::str_wrap(ancestor_name,width = 20),
                        # size = ~ontLvl,
                        color = ~ontLvl,
                        colors = colors,
                        hovertext = ~ stringr::str_wrap(
                          paste(
                            paste0('<b>HPO_ID</b>: ',HPO_ID),
                            paste0('<b>Phenotype</b>: ',Phenotype),
                            paste0('<b>ontLvl</b>: ',ontLvl),
                            sep = "<br>"),
                          width = 50
                        ),
                        opacity = 1,
                        type = "scatter3d",
                        mode = "markers") |>
    plotly::add_lines(color = ~ontLvl,
                      line = list(shape = "spline"),
                      type = "scatter3d",
                      name = "edge",
                      opacity = .25,
                      mode = "lines",
                      hoverinfo = "none",
                      showlegend = TRUE) |>
    # plotly::add_paths()
    # plotly::add_mesh()
    plotly::add_surface(
      data = kd,
      x = ~x,
      y = ~y,
      z = ~z,
      opacity = 1,
      hoverinfo = "none",
      colorscale = list(seq(0,1,length.out=6),
                        pals::gnuplot(n = 6)),
      showlegend = FALSE,
      inherit = FALSE) |>
    plotly::layout(hoverlabel = list(
      align = "left"
      ),
      plot_bgcolor='rgb(15,15,65)',	#tail(colors,1),
      paper_bgcolor='rgb(15,15,65)',
      scene = lapply(stats::setNames(c("xaxis","yaxis","zaxis"),
                                       c("xaxis","yaxis","zaxis")),
                       function(x){list(showgrid = FALSE,
                                        showline = FALSE,
                                        showspikes = FALSE,
                                        zeroline = FALSE,
                                        title = list(text=""),
                                        showticklabels = FALSE)}
      )
    )
  if(isTRUE(add_labels)){
    fig <- fig |>
      plotly::add_text(text = ~label,
                       hoverinfo = "none",
                       showlegend = FALSE)
  }

  # file <- file.path("~/Downloads","hpo_plotly.png")
  # plotly::export(p = fig, file = file)
  # reticulate::py_install(packages = "kaleido",)
  # plotly::save_image(p = fig,file = file, width = 10, height =10)
  return(fig)
}
