#' Phenotypes to \link[GenomicRanges]{GenomicRanges}
#'
#' Convert a HPO phenotype dataframe generated by
#' \link[HPOExplorer]{make_phenos_dataframe}
#' to a \link[GenomicRanges]{GRangesList} split by HPO ID.
#' The resulting object will contain genes (and gene metadata) for all
#' genes associated with each phenotypes.
#' @param keep_seqnames Chromosomes to keep.
#' @inheritParams make_network_object
#' @inheritParams make_phenos_dataframe
#' @inheritParams GenomicRanges::makeGRangesListFromDataFrame
#' @returns A \link[GenomicRanges]{GRangesList}.
#'
#' @export
#' @importFrom data.table merge.data.table as.data.table
#' @examples
#' phenos <- make_phenos_dataframe(ancestor = "Neurodevelopmental delay")
#' grl <- phenos_to_granges(phenos = phenos)
phenos_to_granges <- function(phenos,
                              phenotype_to_genes =
                                load_phenotype_to_genes(),
                              hpo = get_hpo(),
                              keep_seqnames = c(seq_len(22),"X","Y"),
                              split.field = "ID",
                              verbose = TRUE){
  # templateR:::source_all()
  # templateR:::args2vars(phenos_to_granges)
  requireNamespace("GenomicRanges")

  messager("Converting phenos to",
           if(is.null(split.field))"GRanges."else"GRangesList.",
           v=verbose)
  if(is.character(phenos)){
   phenos <- data.table::data.table(HPO_ID=names(phenos),
                                    Phenotype=unname(phenos))
  }
  phenos <- add_hpo_id(phenos = phenos,
                       phenotype_to_genes = phenotype_to_genes,
                       hpo = hpo)
  phenos_genes <- get_gene_lists(phenotypes = phenos$HPO_ID,
                                 phenotype_to_genes = phenotype_to_genes,
                                 hpo = hpo,
                                 as_list = FALSE)
  gr <- get_gene_lengths(gene_list = phenos_genes$Gene,
                         keep_seqnames = keep_seqnames,
                         verbose = verbose)
  #### Merge in gene data ####
  gr_dt <- data.table::merge.data.table(
    phenos_genes,
    data.table::as.data.table(gr),
    by.x = "Gene",
    by.y = "symbol")
  gr <- GenomicRanges::makeGRangesFromDataFrame(df = gr_dt,
                                                keep.extra.columns = TRUE)
  if(is.null(split.field)) {
    return(gr)
  } else {
    return(
      GenomicRanges::split(gr,
                           f = GenomicRanges::mcols(gr)[[split.field]])
    )
  }
}
